---
title: "draft"
author: "Group 5"
date: '2022-12-02'
output: html_document
---

Introduction  
The data is Flight Prices for One way flights found on Expedia. We sought to find what factors affect the price of a plane ticket.   

We made a multiple linear regression model to see what factors affect the price of ticket from that specific departing airport.  

Based on our analysis we conclude that  

Statistical Analysis  
The data set is a 31GB Kaggle Data set of Flight ticket found on Expedia between 04/16/2022 and 10/05/2022. We split the 31GB data set into 16 smaller data sets based on departing airport.   

Graphs / Summaries  

We ran 16 jobs on CHTC. The typical job took 10 minutes to run, 1 GB of memory, 2 GB of disk space.   

A weaknesses to our analysis is that we aren't taking into consideration a temporal affect of ticket prices.     

Conclusion  
We wanted to see what factors affected the price of a plane ticket. Based on our analysis 

Future analysis we could add the temporal affect of the ticket. We did not look at that aspect for this analysis.

Post Conclusion  
Abby, Anna, Marwa: All contributed to: Writing Proposal, Writing code, Making presentation, writing the Report 
 



